package com.model.pojo;
// Generated Oct 3, 2019 2:08:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Akun generated by hbm2java
 */
public class Akun  implements java.io.Serializable {


     private Integer idAkun;
     private String nama;
     private String alamat;
     private String jk;
     private String tempatLahir;
     private Date tanggalLahir;
     private String noTelp;
     private String username;
     private String password;

    public Akun() {
    }

    public Akun(String nama, String alamat, String jk, String tempatLahir, Date tanggalLahir, String noTelp, String username, String password) {
       this.nama = nama;
       this.alamat = alamat;
       this.jk = jk;
       this.tempatLahir = tempatLahir;
       this.tanggalLahir = tanggalLahir;
       this.noTelp = noTelp;
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getJk() {
        return this.jk;
    }
    
    public void setJk(String jk) {
        this.jk = jk;
    }
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


