package com.model.pojo;
// Generated Oct 3, 2019 2:08:48 PM by Hibernate Tools 4.3.1



/**
 * Bis generated by hbm2java
 */
public class Bis  implements java.io.Serializable {


     private Integer idBis;
     private String namaBis;
     private String karoseri;
     private String merkMesin;
     private String warna;
     private int kapasitas;

    public Bis() {
    }

    public Bis(String namaBis, String karoseri, String merkMesin, String warna, int kapasitas) {
       this.namaBis = namaBis;
       this.karoseri = karoseri;
       this.merkMesin = merkMesin;
       this.warna = warna;
       this.kapasitas = kapasitas;
    }
   
    public Integer getIdBis() {
        return this.idBis;
    }
    
    public void setIdBis(Integer idBis) {
        this.idBis = idBis;
    }
    public String getNamaBis() {
        return this.namaBis;
    }
    
    public void setNamaBis(String namaBis) {
        this.namaBis = namaBis;
    }
    public String getKaroseri() {
        return this.karoseri;
    }
    
    public void setKaroseri(String karoseri) {
        this.karoseri = karoseri;
    }
    public String getMerkMesin() {
        return this.merkMesin;
    }
    
    public void setMerkMesin(String merkMesin) {
        this.merkMesin = merkMesin;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public int getKapasitas() {
        return this.kapasitas;
    }
    
    public void setKapasitas(int kapasitas) {
        this.kapasitas = kapasitas;
    }




}


