package com.model.pojo;
// Generated Oct 3, 2019 2:08:48 PM by Hibernate Tools 4.3.1


import com.dao.BlogDAO;
import com.dao.GaleriDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Transient;
import javax.servlet.http.Part;

/**
 * Blog generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Blog  implements java.io.Serializable {


     private Integer idBlog;
     private String lokasi;
     private String judul;
     private Date tanggal;
     private String isi;

    public Blog() {
    }

    public Blog(String lokasi, String judul, Date tanggal, String isi) {
       this.lokasi = lokasi;
       this.judul = judul;
       this.tanggal = tanggal;
       this.isi = isi;
    }
   
    public Integer getIdBlog() {
        return this.idBlog;
    }
    
    public void setIdBlog(Integer idBlog) {
        this.idBlog = idBlog;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }

    @Transient
    private Part image;
    @Transient
     private boolean uploaded;
    
    public Part getImage() {
        return image;
    }

    public void setImage(Part image) {
        this.image = image;
    }

    public String doUpload() {
                    String path = null;
                    String pathValue = null;
                    try {
                            InputStream in = image.getInputStream();
                            File f = new File("C:\\Users\\deniw\\Documents\\NetBeansProjects\\Bejeu2\\web\\user\\img\\portfolio\\"+image.getSubmittedFileName());
                            f.createNewFile();
                            FileOutputStream out = new FileOutputStream(f);

                            byte[] buffer = new byte[1024];
                            int length;
                            while ((length=in.read(buffer))>0){
                                    out.write(buffer, 0, length);
                            }
                            out.close();
                            in.close();

                            path = String.valueOf(f.getAbsolutePath());
                            pathValue = "user/img/portfolio/"+image.getSubmittedFileName();
                            System.out.println("upload success");
                    } catch (Exception e) {
                            System.out.println(e);
                    }
                    return pathValue;
            }

        public void addServicelist() {
                    BlogDAO dao = new BlogDAO();
                    setLokasi(doUpload());
                    dao.addNewService(this);
            }

    }


