package com.model.pojo;
// Generated Oct 3, 2019 2:08:48 PM by Hibernate Tools 4.3.1

import com.dao.GaleriDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Transient;
import javax.servlet.http.Part;




/**
 * Galeri generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Galeri  implements java.io.Serializable {


     private Integer idGambar;
     private String picture;
     private String caption;

    public Galeri() {
    }

    public Galeri(String picture, String caption) {
       this.picture = picture;
       this.caption = caption;
    }
   
    public Integer getIdGambar() {
        return this.idGambar;
    }
    
    public void setIdGambar(Integer idGambar) {
        this.idGambar = idGambar;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    
    @Transient
    private Part image;
    @Transient
     private boolean uploaded;
    
    public Part getImage() {
        return image;
    }

    public void setImage(Part image) {
        this.image = image;
    }
    
//    public String doUpload() {
//		String path = null;
//		String pathValue = null;
//		try {
//			InputStream in = getImage().getInputStream();
//			File f = new File("C:\\Users\\deniw\\Documents\\NetBeansProjects\\Bejeu2\\web\\user\\img\\portfolio\\"+getImage().getSubmittedFileName());
//			f.createNewFile();
//			FileOutputStream out = new FileOutputStream(f);
//			
//			byte[] buffer = new byte[1024];
//			int length;
//			while ((length=in.read(buffer))>0){
//				out.write(buffer, 0, length);
//			}
//			out.close();
//			in.close();
//			
//			path = String.valueOf(f.getAbsolutePath());
//			setUploaded(true);
//			pathValue = "user\\img\\portfolio\\"+getImage().getSubmittedFileName();
//			System.out.println("upload success");
//		} catch (Exception e) {
//			System.out.println(e);
//		}
//		return pathValue;
//	}
    
    public boolean isUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }
    public String doUpload() {
		String path = null;
		String pathValue = null;
		try {
			InputStream in = image.getInputStream();
			File f = new File("C:\\Users\\deniw\\Documents\\NetBeansProjects\\Bejeu2\\web\\user\\img\\portfolio\\"+image.getSubmittedFileName());
			f.createNewFile();
			FileOutputStream out = new FileOutputStream(f);
			
			byte[] buffer = new byte[1024];
			int length;
			while ((length=in.read(buffer))>0){
				out.write(buffer, 0, length);
			}
			out.close();
			in.close();
			
			path = String.valueOf(f.getAbsolutePath());
			pathValue = "user/img/portfolio/"+image.getSubmittedFileName();
			System.out.println("upload success");
		} catch (Exception e) {
			System.out.println(e);
		}
		return pathValue;
	}
    
    public void addServicelist() {
		GaleriDAO dao = new GaleriDAO();
		setPicture(doUpload());
		dao.addNewService(this);
	}


}


