package com.model.pojo;
// Generated Oct 3, 2019 2:08:48 PM by Hibernate Tools 4.3.1



/**
 * Saran generated by hbm2java
 */
public class Saran  implements java.io.Serializable {


     private Integer idSaran;
     private String nama;
     private String email;
     private String subjek;
     private String pesan;

    public Saran() {
    }

    public Saran(String nama, String email, String subjek, String pesan) {
       this.nama = nama;
       this.email = email;
       this.subjek = subjek;
       this.pesan = pesan;
    }
   
    public Integer getIdSaran() {
        return this.idSaran;
    }
    
    public void setIdSaran(Integer idSaran) {
        this.idSaran = idSaran;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSubjek() {
        return this.subjek;
    }
    
    public void setSubjek(String subjek) {
        this.subjek = subjek;
    }
    public String getPesan() {
        return this.pesan;
    }
    
    public void setPesan(String pesan) {
        this.pesan = pesan;
    }




}


